# Generated by Django 5.2.9 on 2025-12-06 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_add_soft_delete_and_partial_unique'),
        ('companies', '0002_initial'),
    ]

    operations = [
    ]
