# Generated by Django 6.0 on 2025-12-06 08:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('location', models.CharField(max_length=100)),
                ('job_type', models.CharField(choices=[('FULL_TIME', 'Toàn thời gian'), ('PART_TIME', 'Bán thời gian'), ('FREELANCE', 'Freelance'), ('INTERNSHIP', 'Thực tập')], default='FULL_TIME', max_length=20)),
                ('salary_min', models.IntegerField(blank=True, null=True)),
                ('salary_max', models.IntegerField(blank=True, null=True)),
                ('is_negotiable', models.BooleanField(default=False)),
                ('description', models.TextField()),
                ('requirements', models.TextField()),
                ('benefits', models.TextField()),
                ('deadline', models.DateField()),
                ('status', models.CharField(choices=[('DRAFT', 'Nháp'), ('PUBLISHED', 'Đang đăng'), ('CLOSED', 'Đã đóng')], default='PUBLISHED', max_length=20)),
                ('views_count', models.IntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='companies.company')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
