# Generated by Django 5.2.9 on 2025-12-06 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_merge_20251207_0541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='deadline',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='location',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Nháp'), ('PUBLISHED', 'Đang đăng'), ('CLOSED', 'Đã đóng')], db_index=True, default='PUBLISHED', max_length=20),
        ),
        migrations.AlterModelTable(
            name='job',
            table='jobs_job',
        ),
    ]
