# Generated by Django 6.0 on 2025-12-06 15:06

import apps.resumes.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='education',
            options={'ordering': ['-start_date']},
        ),
        migrations.AlterModelOptions(
            name='workexperience',
            options={'ordering': ['-start_date']},
        ),
        migrations.AddField(
            model_name='resume',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='resumes/pdf_output/', verbose_name='Generated PDF File'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='file',
            field=models.FileField(blank=True, help_text='Tải lên CV đính kèm (PDF, DOC, DOCX, ảnh). Tối đa 5MB.', null=True, upload_to='resumes/files/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'jpg', 'jpeg', 'png']), apps.resumes.models.validate_file_size]),
        ),
    ]
