# Generated by Django 6.0 on 2025-12-06 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicepackage',
            name='allow_unlimited_posting',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='servicepackage',
            name='allow_view_contact',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='servicepackage',
            name='package_type',
            field=models.CharField(choices=[('CREDIT', 'Gói mua lượt (Credits)'), ('SUBSCRIPTION', 'Gói thuê bao (Subscription)')], default='CREDIT', max_length=20),
        ),
        migrations.AlterField(
            model_name='servicepackage',
            name='job_posting_limit',
            field=models.IntegerField(default=0),
        ),
    ]
