# Generated by Django 6.0 on 2025-12-06 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_view_contact',
            field=models.BooleanField(default=False, help_text='Được phép xem thông tin liên hệ ứng viên'),
        ),
        migrations.AddField(
            model_name='user',
            name='has_unlimited_posting',
            field=models.BooleanField(default=False, help_text='Được phép đăng tin không giới hạn'),
        ),
    ]
