# Generated by Django 5.2.9 on 2025-12-06 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_add_indexes'),
        ('users', '0002_add_optimistic_locking_version'),
        ('users', '0002_user_can_view_contact_user_has_unlimited_posting'),
    ]

    operations = [
    ]
