# Generated by Django 6.0 on 2025-12-06 08:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cv_file', models.FileField(upload_to='applications/cvs/')),
                ('cover_letter', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Chờ duyệt'), ('VIEWED', 'Nhà tuyển dụng đã xem'), ('INTERVIEW', 'Mời phỏng vấn'), ('REJECTED', 'Từ chối'), ('ACCEPTED', 'Đã trúng tuyển')], default='PENDING', max_length=20)),
                ('note', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
