# Generated by Django 6.0 on 2025-12-06 15:04

import apps.applications.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='application',
            name='cv_file',
            field=models.FileField(help_text='Tải lên CV đính kèm (PDF, DOC, DOCX). Tối đa 5MB.', upload_to='applications/cvs/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx']), apps.applications.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='application',
            name='note',
            field=models.TextField(blank=True, help_text='Ghi chú nội bộ của Nhà tuyển dụng về ứng viên này', null=True),
        ),
    ]
