# Generated by Django 6.0 on 2025-12-06 16:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_alter_application_options_alter_application_cv_file_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewSchedule',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('interview_date', models.DateTimeField(help_text='Thời gian bắt đầu phỏng vấn')),
                ('duration_minutes', models.IntegerField(default=60, help_text='Thời lượng dự kiến (phút)')),
                ('location', models.CharField(blank=True, help_text='Địa điểm offline (nếu có)', max_length=255)),
                ('meeting_link', models.URLField(blank=True, help_text='Link họp online (Google Meet/Zoom)', null=True)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Đã lên lịch'), ('COMPLETED', 'Đã hoàn thành'), ('CANCELLED', 'Đã hủy')], default='SCHEDULED', max_length=20)),
                ('note', models.TextField(blank=True, help_text='Ghi chú cho ứng viên (VD: Mang theo laptop)')),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='interview_schedule', to='applications.application')),
                ('interviewer', models.ForeignKey(help_text='Người phỏng vấn (nếu có)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interviews_conducting', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
